# Generated by Django 6.0.8 on 2026-08-17 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CLIENT_CREATED', 'Client created'), ('CLIENT_UPDATED', 'Client updated'), ('CLIENT_DELETED', 'Client deleted'), ('TRANSACTION_CREATED', 'Transaction created'), ('TRANSACTION_UPDATED', 'Transaction updated'), ('TRANSACTION_CONFIRMED', 'Transaction confirmed'), ('MEMBER_INVITED', 'Member invited'), ('MEMBER_ROLE_UPDATED', 'Member role updated'), ('MEMBER_REMOVED', 'Member removed'), ('INVITATION_ACCEPTED', 'Invitation accepted')], max_length=50)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx')],
            },
        ),
    ]
