# Generated by Django 6.0.8 on 2026-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence__gte', 0), ('ai_confidence__lte', 1)), name='transaction_ai_confidence_0_1'),
        ),
    ]
