# Generated by Django 6.0.8 on 2026-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_deleted_at_client_is_deleted'),
        ('transactions', '0002_transaction_transaction_ai_confidence_0_1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('source_transaction_id', ''), _negated=True), fields=('client', 'source_transaction_id'), name='transaction_client_source_unique'),
        ),
    ]
